# Generated by Django 3.0.4 on 2020-04-10 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20200408_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 16, 46, 8, 584588)),
        ),
    ]
