# Generated by Django 3.0.4 on 2020-04-10 04:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20200410_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 4, 47, 22, 475054, tzinfo=utc)),
        ),
    ]
